### ISSUE TITLE
Issues with regex pattern matching in collections editor

### ISSUE THREAD

**Issue by uchilaka** [directus/directus-8-legacy#2029]
I'm capturing steps to re-create. For now, some notes:

I've tried a number of regex formats with no luck in the collection editor (see snippet). It saves the collection definition fine, but when I'm creating items, doesn't let me save regardless of inputting values that pass the unit tests @ this link: https://regex101.com/r/xdkcR1/1/tests. 

Notes:
```js
#!/usr/local/bin/node
// Validate between 2 and 6 digits ONLY
// Unit tests here: https://regex101.com/r/xdkcR1/1
const REGEX_PATTERN=/^[0-9]{2,6}$/;
console.log("Should succeed", REGEX_PATTERN.test(8080));
console.log("Should fail", !REGEX_PATTERN.test("8080 "));
```

Docker compose script:

```yaml
version: "3.6"

services:
  directus-db:
    container_name: directus-cms-db
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "Directus CMS Database"
      MYSQL_ROOT_PASSWORD: ??
      # MYSQL_USER: ??
      # MYSQL_PASSWORD: ??
    # Commenting out the ports will ONLY expose port to directus CMS
    ports:
      - 7706:3306
    volumes:
      - ./data/mysql:/var/lib/mysql

  # API
  directus-cms:
    image: directus/api:2.0.17
    container_name: directus-cms
    restart: unless-stopped
    environment:
      DATABASE_HOST: directus-db
      DATABASE_NAME: "Directus CMS Database"
      DATABASE_CHARSET: utfmb4
      DATABASE_ENGINE: InnoDB
      DATABASE_TYPE: mysql
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: ??
      ADMIN_EMAIL: ??
      ADMIN_PASSWORD: ??
    ports:
      - 7700:80
    depends_on:
      - directus-db

  # Dashboard
  directus-dashboard:
    image: directus/app:7.0.17
    container_name: directus-dashboard
    restart: unless-stopped
    environment:
      APP_TIMEZONE: America/New_York
      API_ENDPOINT: "API; http://localhost:7700/_/"
    ports:
      - 7800:80
    depends_on:
      - directus-db
```
