### ISSUE TITLE
Thumbnail file request is HTTP instead of HTTPS.

### ISSUE THREAD

**Issue by benjaminbours** [directus/directus-8-legacy#2133]
• Version of Directus **8.7.2**
• Server, OS & Database Details **Docker image 8.7.2**

• Error Messages
Client sent an HTTP request to an HTTPS server.
• Steps to Reproduce
 Upload an image in a collection item. The file is correctly upload but the request to get the thumbnail of the assets is done in http, instead of https like the other request.
• Relevant Info, Screenshots, Schema & Logs

<img width="1680" alt="Screenshot 2020-07-24 at 19 05 01" src="https://user-images.githubusercontent.com/8804297/88416476-95ee1d00-cde0-11ea-80db-69b54597ca35.png">

Here is my docker-compose
```yaml
version: "3"
services:
  #
  # Database
  #
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "directus"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports: # Expose it if you want to access MySQL server
      - 3306:3306
    networks:
      - database
    volumes:
      - ./db_backup:/var/lib/mysql

  #
  # Directus instance.
  # This should serve directus and won't work before database
  # is properly installed by running the installer.
  #
  directus:
    image: directus/directus:v8.7.2-apache
    environment:
      # App
      # DIRECTUS_USE_ENV: 0
      DIRECTUS_ENV: "production"

      # These are now required, make sure to always set
      # to something unique while in production
      DIRECTUS_AUTH_PUBLICKEY: "${DIRECTUS_PUBLICKEY}"
      DIRECTUS_AUTH_SECRETKEY: "${DIRECTUS_SECRETKEY}"

      # Database
      DIRECTUS_DATABASE_HOST: "mysql"
      DIRECTUS_DATABASE_PORT: "3306"
      DIRECTUS_DATABASE_NAME: "directus"
      DIRECTUS_DATABASE_USERNAME: "${DB_USER}"
      DIRECTUS_DATABASE_PASSWORD: "${DB_PASSWORD}"

    # Uploads gets saved in uploads folder
    volumes:
      - ./data/config:/var/directus/config
      - ./data/uploads:/var/directus/public/uploads

    ports:
      - 8080:80

    networks:
      - database
      - http

  #
  # Caddy for HTTPS
  # https://caddyserver.com/docs/
  #
  caddy:
    image: caddy/caddy
    command: "caddy reverse-proxy --to http://directus"
    ports:
      - 8443:443
    networks:
      - http

networks:
  database:
  http:

```
