### ISSUE TITLE
Unable to connect to mysql database outside of docker container

### ISSUE THREAD

**Issue by beningreenjam** [directus/directus-8-legacy#2152]
I'm attempting to use the official `directus/directus:v8-apache` docker image to connect to a mysql database outside of the container.

After successfully starting the container, I'm able to reach step 4 of the project setup UI at `/admin/#/install`. I enter the following details (which I have confirmed are correct via testing through my local cli):

host: 127.0.0.1
port: 3306
database user: cms
database password: secret
database name: cms

That's when I get the error "Invalid database connection".

Below is my docker-compose.yaml config

```
version: '3'

services:
  directus:
    image: directus/directus:v8-apache
    restart: on-failure
    ports:
      - ${APACHE_PORT:-8000}:80
    environment:
      - DIRECTUS_USE_ENV="1"
      - DIRECTUS_APP_ENV=${APP_ENV:-production}
      - DIRECTUS_AUTH_PUBLICKEY=${AUTH_PUBLICKEY:-random}
      - DIRECTUS_AUTH_SECRETKEY=${AUTH_SECRETKEY:-secret}
      - DIRECTUS_DATABASE_TYPE=${DB_TYPE:-mysql}
      - DIRECTUS_DATABASE_HOST=${DB_HOST:-127.0.0.1}
      - DIRECTUS_DATABASE_PORT=${DB_CONTAINER_PORT:-3306}
      - DIRECTUS_DATABASE_NAME=${DB_DATABASE:-cms}
      - DIRECTUS_DATABASE_USERNAME=${DB_USER:-cms}
      - DIRECTUS_DATABASE_PASSWORD=${DB_PASSWORD:-secret}
    volumes:
      - ./_data/config:/var/directus/config
      - ./_data/uploads:/var/directus/public/uploads

```

Running on:
Mac OS Catalina 10.5.3
Docker engine 19.03.8
Docker compose 1.25.4
PHP 7.3.13
Mysql 5.7.22
